FROM python:3.11-slim

WORKDIR /app

COPY ../dashboard/ ./dashboard/

RUN pip install --no-cache-dir -r dashboard/requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
