FROM python:3.11-slim

WORKDIR /app

COPY ../api/ ./api/
COPY ../ml-python/models/ ./models/

RUN pip install --no-cache-dir -r api/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]